name: Build .NET setup

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "TestcontainersDemo"
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core SDK 7.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Test
        run: dotnet test --verbosity normal
